### ISSUE TITLE
Migrate to GeoJSON

### ISSUE THREAD

**Issue by johnjohndoe** [CodeforKarlsruhe/wo-ist-markt#3]
I looked into your project and thought of redeploying it for Berlin. I wonder why you did create a [custom JSON format for the data](https://github.com/CodeforKarlsruhe/wo-ist-markt/blob/gh-pages/markt.json). Is there a particular reason you decided for it? I would like to discuss with you if we can change the data format plus Leaflet code to use the **standardized GeoJSON** format. This will make it much **easier to reploy** the project for other cities since CSV or Shapefiles can be easily converted in to GeoJSON.

**Comment by torfuspolymorphus** [comment]
The current JSON data is a general representation of the underlying data, without special focus on the coordinates. Personally, I think that GeoJSON adds a lot of overhead which is often unnecessary, especially for simple datasets like this one.

Nevertheless suggestions/PRs regarding this issue are very welcome -- anything that makes redeployments easier is usually a good idea.

**Comment by johnjohndoe** [comment]
What is the representation of the original data? Are you converting from a CSV file? I would like to automate the conversion as much as possible since the list of markets and their properties might change and the conversion into the JSON format should not be a manual process.

**Comment by torfuspolymorphus** [comment]
The current JSON file was manually written using data available in non-structured formats. There is no automated process in place, i.e. corrections and updates are done manually and directly in the JSON. You therefore don't have to worry about breaking anything here :)

**Comment by torfsen** [comment]
Closed by #7.
